version: '3.8'
services:
  postgres:
    image: postgres:10.3
    restart: always
    environment:
      - POSTGRES_USER=db-manager
      - POSTGRES_PASSWORD=R5a5hazt3$ddl4f9
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5000:5432'
volumes:
  postgres:
